# File automatically generated by "nac2cdfg".
# Filename: ansic.sh
# Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

#!/bin/bash

make -if ansic.mk clean
make -if ansic.mk
exit 0
