-- File automatically generated by "nac2cdfg".
-- Filename: mandel_cdt_pkg.vhd
-- Date: 12 October 2013 05:10:59 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package mandel_cdt_pkg is


end mandel_cdt_pkg;
