-- File automatically generated by "nac2cdfg".
-- Filename: mandel_pkg.vhd
-- Date: 12 October 2013 05:10:59 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package mandel_pkg is

  component checkpixel
    port (
      clk : in std_logic;
      reset : in std_logic;
      start : in std_logic;
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      flag : in std_logic_vector(31 downto 0);
      done : out std_logic;
      ready : out std_logic
    );
  end component;

end mandel_pkg;
