
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (e:\hercules\thirdparty\lance-devel\BIN_WIN2000\compile.exe) on
     Saturday, Oct 12, 2013 at 20:39:26
$ */

void isqrt(unsigned ,unsigned *);

void isqrt(unsigned x_2,unsigned *outp_3)
{
 unsigned m_5;
 unsigned y_6;
 unsigned b_7;
 unsigned x0_8;
 int t1;
 int t2;
 unsigned t3;
 unsigned t4;
 unsigned t5;
 int t6;
 int t14;
 unsigned t7;
 unsigned t8;
 int t9;
 int t12;
 unsigned t13;
 unsigned t10;
 unsigned t11;


 /* 4 "isqrt.i" */
 /* $ m = 0x1 << (32 -2);$ */

	t1 = 32 - 2;
	t2 = 1 << t1;
	t3 = (unsigned )t2;
	m_5 = t3;

 /* 5 "isqrt.i" */
 /* $ y = 0;$ */

	t4 = (unsigned )0;
	y_6 = t4;

 /* 6 "isqrt.i" */
 /* $ x0 = x;$ */

	x0_8 = x_2;

 /* 7 "isqrt.i" */
 /* $ while (m != 0)$ */

 LL4:
	t5 = (unsigned )0;
	t6 = m_5 != t5;
	t14 = !t6;
	if (t14) goto LL1;


 /* 9 "isqrt.i" */
 /* $ b = y | m;$ */

	t7 = y_6 | m_5;
	b_7 = t7;

 /* 10 "isqrt.i" */
 /* $ y = y >> 1;$ */

	t8 = y_6 >> 1;
	y_6 = t8;

 /* 11 "isqrt.i" */
 /* $ if (x0 >= b)$ */

	t9 = x0_8 >= b_7;
	t12 = !t9;
	if (t12) goto LL3;


 /* 13 "isqrt.i" */
 /* $ x0 = x0 - b;$ */

	t10 = x0_8 - b_7;
	x0_8 = t10;

 /* 14 "isqrt.i" */
 /* $ y = y | m;$ */

	t11 = y_6 | m_5;
	y_6 = t11;

 /* 11 "isqrt.i" */
 /* $ if (x0 >= b)$ */

 LL3:

 /* 16 "isqrt.i" */
 /* $ m = m >> 2;$ */

	t13 = m_5 >> 2;
	m_5 = t13;

 /* 7 "isqrt.i" */
 /* $ while (m != 0)$ */

 LL2:
	goto LL4;

 LL1:

 /* 18 "isqrt.i" */
 /* $ *outp = y;$ */

	*outp_3 = y_6;

 /* 0 "???" */
 /* $ ???$ */

	return;
}
