# File automatically generated by "nac2cdfg".
# Filename: ansic.sh
# Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

#!/bin/bash

make -if ${CDFG2HDL_PATH}/../tests/ansic/popcount/ansic.mk clean
make -if ${CDFG2HDL_PATH}/../tests/ansic/popcount/ansic.mk
exit 0
