-- File automatically generated by "nac2cdfg".
-- Filename: popcount_pkg.vhd
-- Date: 24 October 2013 06:07:45 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package popcount_pkg is


end popcount_pkg;
