
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (e:\hercules\thirdparty\lance-devel\BIN_WIN2000\compile.exe) on
     Saturday, Oct 12, 2013 at 20:23:27
$ */

int popcount(int );

int popcount(int inp_2)
{
 int data_4;
 int count_5;
 int t1;
 int t5;
 int t2;
 int t3;
 int t4;


 /* 4 "popcount.i" */
 /* $ data = inp;$ */

	data_4 = inp_2;

 /* 5 "popcount.i" */
 /* $ count = 0;$ */

	count_5 = 0;

 /* 6 "popcount.i" */
 /* $ while (data != 0)$ */

 LL3:
	t1 = data_4 != 0;
	t5 = !t1;
	if (t5) goto LL1;


 /* 8 "popcount.i" */
 /* $ count = count + (data & 0x1);$ */

	t2 = data_4 & 1;
	t3 = count_5 + t2;
	count_5 = t3;

 /* 9 "popcount.i" */
 /* $ data = data >> 0x1;$ */

	t4 = data_4 >> 1;
	data_4 = t4;

 /* 6 "popcount.i" */
 /* $ while (data != 0)$ */

 LL2:
	goto LL3;

 LL1:

 /* 11 "popcount.i" */
 /* $ return count;$ */

	return count_5;

}
