-- File automatically generated by "nac2cdfg".
-- Filename: gmp_fact_cdt_pkg.vhd
-- Date: 16 October 2013 11:51:20 AM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package gmp_fact_cdt_pkg is


end gmp_fact_cdt_pkg;
