-- File automatically generated by "nac2cdfg".
-- Filename: gmp_fibo_cdt_pkg.vhd
-- Date: 12 October 2013 02:34:32 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package gmp_fibo_cdt_pkg is


end gmp_fibo_cdt_pkg;
