-- File automatically generated by "nac2cdfg".
-- Filename: fibo_pkg.vhd
-- Date: 31 May 2013 12:18:42 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package fibo_pkg is


end fibo_pkg;
