-- File automatically generated by "nac2cdfg".
-- Filename: icbrt_pkg.vhd
-- Date: 12 October 2013 04:22:53 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package icbrt_pkg is


end icbrt_pkg;
