-- File automatically generated by "nac2cdfg".
-- Filename: c2vwalsh_pkg.vhd
-- Date: 12 October 2013 02:31:43 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package c2vwalsh_pkg is


end c2vwalsh_pkg;
