-- File automatically generated by "nac2cdfg".
-- Filename: sierpinski_pkg.vhd
-- Date: 12 October 2013 02:00:24 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package sierpinski_pkg is


end sierpinski_pkg;
