-- File automatically generated by "nac2cdfg".
-- Filename: eda_pkg.vhd
-- Date: 31 May 2013 11:08:47 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package eda_pkg is


end eda_pkg;
