-- File automatically generated by "nac2cdfg".
-- Filename: fir_cdt_pkg.vhd
-- Date: 12 October 2013 04:36:42 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package fir_cdt_pkg is

  type cdt000_type is array (9 downto 0) of std_logic_vector(31 downto 0);
  type cdt001_type is array (7 downto 0) of std_logic_vector(31 downto 0);
  subtype v_type is cdt000_type;
  subtype a_type is cdt001_type;

end fir_cdt_pkg;
