-- File automatically generated by "nac2cdfg".
-- Filename: bitrev_pkg.vhd
-- Date: 12 October 2013 12:34:16 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package bitrev_pkg is


end bitrev_pkg;
