# File automatically generated by "cdfg2hdl".
# Filename: eda
# Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

#!/bin/bash

make -if eda.mk clean
make -if eda.mk init
make -if eda.mk run

if [ "$SECONDS" -eq 1 ]
then
  units=second
else
  units=seconds
fi
echo "This script has been running for $SECONDS $units."
exit 0
