-- File automatically generated by "cdfg2hdl".
-- Filename: gcd_tb.vhd
-- Date: 30 May 2013 11:54:34 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE, STD;
use STD.textio.all;
use WORK.std_logic_textio.all;
use IEEE.numeric_std.all;
use WORK.gcd_cdt_pkg.all;
use WORK.std_logic_1164_tinyadditions.all;
use IEEE.std_logic_1164.all;

entity gcd_tb is
end gcd_tb;

architecture tb_arch of gcd_tb is
  component gcd
    port (
      clk : in std_logic;
      reset : in std_logic;
      start : in std_logic;
      a : in std_logic_vector(15 downto 0);
      b : in std_logic_vector(15 downto 0);
      outp : out std_logic_vector(15 downto 0);
      done : out std_logic;
      ready : out std_logic
    );
  end component;
  signal clk : std_logic;
  signal reset : std_logic;
  signal start : std_logic;
  signal a : std_logic_vector(15 downto 0);
  signal b : std_logic_vector(15 downto 0);
  signal outp : std_logic_vector(15 downto 0);
  signal done : std_logic;
  signal ready : std_logic;
  -- Profiling signals
  signal ncycles : integer;
  -- Constant declarations
  constant CLK_PERIOD : time := 10 ns;
  -- Declare test data file and results file
  file TestDataFile: text open read_mode is "gcd_test_data.txt";
  file ResultsFile: text open write_mode is "gcd_alg_test_results.txt";
begin
  uut : gcd
    port map (
      clk => clk,
      reset => reset,
      start => start,
      a => a,
      b => b,
      outp => outp,
      ready => ready,
      done => done
    );

  CLK_GEN_PROC: process(clk)
  begin
    if (clk = 'U') then
      clk <= '1';
    else
      clk <= not clk after CLK_PERIOD/2;
    end if;
  end process CLK_GEN_PROC;

  RESET_START_STIM: process
  begin
    reset <= '1';
    start <= '0';
    wait for CLK_PERIOD;
    reset <= '0';
    start <= '1';
    wait for 536870911*CLK_PERIOD;
  end process RESET_START_STIM;

  PROFILING: process(clk, reset, done)
  begin
    if (reset = '1' or done = '1') then
      ncycles <= 0;
    elsif (clk = '1' and clk'EVENT) then
      ncycles <= ncycles + 1;
    end if;
  end process PROFILING;

  GCD_BENCH: process
    variable a_v : unsigned(15 downto 0);
    variable a_v_vec : std_logic_vector(15 downto 0);
    variable b_v : unsigned(15 downto 0);
    variable b_v_vec : std_logic_vector(15 downto 0);
    variable outp_v, outp_ref : unsigned(15 downto 0);
    variable outp_v_vec, outp_ref_vec : std_logic_vector(15 downto 0);
    variable ncycles_v: integer;
    variable ntests_v : integer := 1;
    variable ntests_max : integer := 2080;
    variable TestData, BufLine: line;
    variable Passed: std_logic := '1';
  begin
    while not endfile(TestDataFile) loop
      -- Read test data from file
      readline(TestDataFile, TestData);
      hread(TestData, a_v_vec);
      a <= a_v_vec;
      hread(TestData, b_v_vec);
      b <= b_v_vec;
      hread(TestData, outp_ref_vec);
      outp_ref := UNSIGNED(outp_ref_vec);
      wait until done = '1';
      outp_v := UNSIGNED(outp);
      -- Test GCD algorithm
      if (
          (outp_v /= outp_ref)
      ) then
        Passed := '0';
        write(Bufline, string'("GCD error: a="));
        hwrite(Bufline, STD_LOGIC_VECTOR(a));
        write(Bufline, string'("GCD error: b="));
        hwrite(Bufline, STD_LOGIC_VECTOR(b));
        write(Bufline, string'(" outp="));
        hwrite(Bufline, STD_LOGIC_VECTOR(outp_v));
        write(Bufline, string'(" outp_ref="));
        hwrite(Bufline, STD_LOGIC_VECTOR(outp_ref));
        writeline(ResultsFile, Bufline);
      else
        write(Bufline, string'(" a="));
        hwrite(Bufline, STD_LOGIC_VECTOR(a));
        write(Bufline, string'(" b="));
        hwrite(Bufline, STD_LOGIC_VECTOR(b));
        write(Bufline, string'(" outp="));
        hwrite(Bufline, STD_LOGIC_VECTOR(outp));
        write(Bufline, string'(" outp_ref="));
        hwrite(Bufline, STD_LOGIC_VECTOR(outp_ref));
        writeline(ResultsFile, Bufline);
        ncycles_v := ncycles;
        write(Bufline, string'("GCD OK: Number of cycles="));
        write(Bufline, ncycles_v);
        writeline(ResultsFile, Bufline);
      end if;
      if (ntests_v = ntests_max) then
        exit;
      end if;
      ntests_v := ntests_v + 1;
    end loop;
    if (Passed = '1') then
      write(Bufline, string'("GCD algorithm test has passed"));
      writeline(ResultsFile, Bufline);
      -- Automatic end of the current simulation.
      assert false
        report "NONE. End simulation time reached"
        severity failure;
    else
      write(Bufline, string'("GCD algorithm test has not passed"));
      writeline(ResultsFile, Bufline);
      -- Automatic end of the current simulation.
      assert false
        report "ERRORS. End simulation time reached"
        severity failure;
    end if;
    wait for CLK_PERIOD;
  end process GCD_BENCH;

end tb_arch;
