-- File automatically generated by "nac2cdfg".
-- Filename: gcd_pkg.vhd
-- Date: 30 May 2013 11:54:30 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package gcd_pkg is


end gcd_pkg;
