-- File automatically generated by "nac2cdfg".
-- Filename: arraysum_pkg.vhd
-- Date: 31 May 2013 12:16:27 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package arraysum_pkg is


end arraysum_pkg;
