-- File automatically generated by "nac2cdfg".
-- Filename: arraysum_cdt_pkg.vhd
-- Date: 31 May 2013 12:16:27 PM
-- Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013

library IEEE;
use IEEE.std_logic_1164.all;

package arraysum_cdt_pkg is

  type cdt000_type is array (9 downto 0) of std_logic_vector(31 downto 0);
  subtype arr_type is cdt000_type;

end arraysum_cdt_pkg;
