
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (e:\hercules\thirdparty\lance-devel\BIN_WIN2000\compile.exe) on
     Saturday, Oct 12, 2013 at 20:23:01
$ */

unsigned fibo(unsigned );

unsigned fibo(unsigned x_2)
{
 unsigned f0_4;
 unsigned f1_5;
 unsigned k_6;
 unsigned f_7;
 unsigned t1;
 unsigned t2;
 unsigned t3;
 int t7;
 unsigned t4;
 unsigned t5;
 unsigned t6;


 /* 5 "fibo.i" */
 /* $ f0 = 0;$ */

	t1 = (unsigned )0;
	f0_4 = t1;

 /* 6 "fibo.i" */
 /* $ f1 = 1;$ */

	t2 = (unsigned )1;
	f1_5 = t2;

 /* 7 "fibo.i" */
 /* $ k = 2;$ */

	t3 = (unsigned )2;
	k_6 = t3;

 /* 13 "fibo.i" */
 /* $ } while (k <= x);$ */

 LL3:

 /* 9 "fibo.i" */
 /* $ k = k + 1;$ */

	t4 = (unsigned )1;
	t5 = k_6 + t4;
	k_6 = t5;

 /* 10 "fibo.i" */
 /* $ f = f1 + f0;$ */

	t6 = f1_5 + f0_4;
	f_7 = t6;

 /* 11 "fibo.i" */
 /* $ f0 = f1;$ */

	f0_4 = f1_5;

 /* 12 "fibo.i" */
 /* $ f1 = f;$ */

	f1_5 = f_7;

 /* 13 "fibo.i" */
 /* $ } while (k <= x);$ */

 LL2:
	t7 = k_6 <= x_2;
	if (t7) goto LL3;

 LL1:

 /* 14 "fibo.i" */
 /* $ return (f);$ */

	return f_7;

}
